"""Lengths adjusted

Revision ID: 1db0b21a1c7f
Revises: 9f3320b4bc15
Create Date: 2024-04-11 14:33:37.056949

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "1db0b21a1c7f"
down_revision: Union[str, None] = "9f3320b4bc15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cpe",
        "deprecatedBy",
        existing_type=mysql.VARCHAR(length=50),
        type_=sa.String(length=250),
        existing_nullable=True,
    )
    op.alter_column(
        "cpe",
        "padded_version",
        existing_type=mysql.VARCHAR(length=50),
        type_=sa.String(length=250),
        existing_nullable=True,
    )
    op.alter_column(
        "cpe",
        "product",
        existing_type=mysql.VARCHAR(length=50),
        type_=sa.String(length=250),
        existing_nullable=True,
    )
    op.alter_column(
        "cpe",
        "vendor",
        existing_type=mysql.VARCHAR(length=50),
        type_=sa.String(length=250),
        existing_nullable=True,
    )
    op.alter_column(
        "cpe",
        "version",
        existing_type=mysql.VARCHAR(length=50),
        type_=sa.String(length=250),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cpe",
        "version",
        existing_type=sa.String(length=250),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "cpe",
        "vendor",
        existing_type=sa.String(length=250),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "cpe",
        "product",
        existing_type=sa.String(length=250),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "cpe",
        "padded_version",
        existing_type=sa.String(length=250),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "cpe",
        "deprecatedBy",
        existing_type=sa.String(length=250),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
