"""ID fields added

Revision ID: 45431ad1d903
Revises: 4a5734ec39b6
Create Date: 2024-04-12 12:57:15.486146

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "45431ad1d903"
down_revision: Union[str, None] = "4a5734ec39b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("capec", sa.Column("id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_capec_id"), "capec", ["id"], unique=True)
    op.add_column("cwe", sa.Column("id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_cwe_id"), "cwe", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cwe_id"), table_name="cwe")
    op.drop_column("cwe", "id")
    op.drop_index(op.f("ix_capec_id"), table_name="capec")
    op.drop_column("capec", "id")
    # ### end Alembic commands ###
