"""Lengths adjusted

Revision ID: 8268a5170930
Revises: 1db0b21a1c7f
Create Date: 2024-04-11 14:35:54.649441

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "8268a5170930"
down_revision: Union[str, None] = "1db0b21a1c7f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cpe",
        "title",
        existing_type=mysql.VARCHAR(length=150),
        type_=sa.String(length=500),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cpe",
        "title",
        existing_type=sa.String(length=500),
        type_=mysql.VARCHAR(length=150),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
