"""Stem length adjusted

Revision ID: 9f3320b4bc15
Revises: 623707ca4795
Create Date: 2024-04-11 14:31:29.621234

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "9f3320b4bc15"
down_revision: Union[str, None] = "623707ca4795"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cpe",
        "stem",
        existing_type=mysql.VARCHAR(length=50),
        type_=sa.String(length=250),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cpe",
        "stem",
        existing_type=sa.String(length=250),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
