name: Security check - Bandit

on:
  - push
  - pull_request

jobs:
  bandit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.10', '3.11' ]
    name: Python ${{ matrix.python-version }} ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Bandit
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Run Bandit security scan
      run: |
        mkdir -p output
        bandit -r . -f txt -o output/security_report.txt || true
        echo "::warning::This workflow does not fail even if Bandit finds security issues."

    - name: Upload Bandit report
      uses: actions/upload-artifact@v4
      with:
        name: security-report-${{ matrix.python-version }}
        path: output/security_report.txt
